# Generated by Django 4.2.7 on 2026-04-25 16:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('bank_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('merchant_id', models.IntegerField(db_index=True)),
                ('response_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['merchant_id', 'idempotency_key'], name='app_idempot_merchan_df2863_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('HOLD', 'Hold'), ('RELEASE', 'Release')], max_length=10)),
                ('reference_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.merchant')),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'created_at'], name='app_transac_merchan_e07dbd_idx'), models.Index(fields=['reference_id'], name='app_transac_referen_10b28e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bank_account_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='app.merchant')),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'status'], name='app_payout_merchan_b0a2c3_idx'), models.Index(fields=['status', 'created_at'], name='app_payout_status_9ff6e8_idx')],
            },
        ),
    ]
